engines:
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
    - acebaf69d448e7cbde3c0e917b449f46
  fixme:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.js"
exclude_paths:
- spec/
